import { Project } from '@/types';

export const projects: Project[] = [
    {
        id: '1',
        character_id: 101,
        user_id: 1,
        title: 'Build Portfolio Website',
        description: 'Create a personal portfolio using Next.js and Tailwind CSS.',
        due_date: new Date('2025-08-15'),
        salt: null,
        difficulty: 'medium',
        is_finished: false,
        is_public: true,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: '2',
        character_id: 102,
        user_id: 2,
        title: 'E-commerce Platform',
        description: 'Develop a full-stack e-commerce app with payment integration.',
        due_date: new Date('2025-08-20'),
        salt: null,
        difficulty: 'hard',
        is_finished: false,
        is_public: false,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: '3',
        character_id: 103,
        user_id: 1,
        title: 'Team Chat Application',
        description: 'Build a real-time team chat app using WebSocket.',
        due_date: new Date('2025-09-01'),
        salt: null,
        difficulty: 'hard',
        is_finished: true,
        is_public: true,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: '4',
        character_id: 104,
        user_id: 3,
        title: 'Expense Tracker App',
        description: 'Create a mobile app to track personal expenses.',
        due_date: new Date('2025-08-10'),
        salt: null,
        difficulty: 'easy',
        is_finished: true,
        is_public: false,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: '5',
        character_id: 105,
        user_id: 4,
        title: 'Admin Dashboard UI',
        description: 'Design an admin dashboard with analytics widgets.',
        due_date: new Date('2025-08-25'),
        salt: null,
        difficulty: 'medium',
        is_finished: false,
        is_public: true,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: '6',
        character_id: 106,
        user_id: 2,
        title: 'AI Chatbot Integration',
        description: 'Integrate GPT chatbot into customer support flow.',
        due_date: new Date('2025-08-18'),
        salt: null,
        difficulty: 'hard',
        is_finished: false,
        is_public: false,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: '7',
        character_id: 107,
        user_id: 1,
        title: 'Blog API Service',
        description: 'Create RESTful APIs for blog CRUD operations.',
        due_date: new Date('2025-08-12'),
        salt: null,
        difficulty: 'medium',
        is_finished: true,
        is_public: true,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: '8',
        character_id: 108,
        user_id: 3,
        title: 'Landing Page Revamp',
        description: 'Redesign landing page for better conversion.',
        due_date: new Date('2025-08-05'),
        salt: null,
        difficulty: 'easy',
        is_finished: true,
        is_public: true,
        created_at: new Date(),
        updated_at: new Date(),
    },
];
